### ISSUE TITLE
Freezing in game issue

### ISSUE THREAD

**Issue by solarblindfull** [Vaelzan/Scenic#5]
Hello ! I'm on Forge 31.2.30 with TerraForged + Biome O'Plenty + Oh The Biomes You'll Go + Quark + Immersive Portals Dimension Stack + Optifine pre 30

When I create a new world, my game freeze for 5 seconds every 20 seconds. It's definitly scenic mod that make me freeze like that because my game work very fine without it. I think it's a render issue or a quark incompatibility.

Can you see what's wrong please ? Thank very much. Have a good day ! :)

**Comment by Vaelzan** [comment]
We use Scenic in a mod pack that has TerraForged, BoP, Quark, and Forge 31.2.31 just fine, so it definitely isn't a compatibility issue with Quark.

When the game freezes like that it's usually the incorrect amount of memory allocated to Java rather than any particular mod at fault.

**Comment by solarblindfull** [comment]
Thank very much for your reply.

I have 16GB DDR4 configuration of which 6GB allocated to minecraft.

If it's not Quark or Terraforged, maybe Immersive Portals Dimension Stack is in fault.

**Comment by Vaelzan** [comment]
My suspicion would be the dimension stacking. We've had to remove Immersive Portals from our packs due to poor performance. :(

**Comment by solarblindfull** [comment]
I think the renders of your mod's models are incompatible with Immersive Portals Dimension Stack because they need to generate twice in different worlds... Thank for your reply. I will not use your mod as long as Immersive Portals or you doesn't find a fix for it

Have a good day

**Comment by Vaelzan** [comment]
I forgot to reply to this when you last commented (and I took a break from working on the mod for several months due to illness), but the models in this mod are all regular JSON models, no custom rendering code at all. I'm quite confident that it isn't something in Scenic causing the problem, otherwise you'd have the same issues with the rendering of regular Minecraft models.
