### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by brendenspencer** [Vaelzan/Scenic#9]
not sure if this is a mod conflict but when I am attacking stuff and hit something fast it crashes my game

**Comment by Vaelzan** [comment]
What makes you think it's the Scenic mod? Can you attach a crash report please?

**Comment by brendenspencer** [comment]
[crash-2020-10-11_19.17.29-client.txt](https://github.com/Vaelzan/Scenic/files/5362873/crash-2020-10-11_19.17.29-client.txt)
[crash-2020-10-11_22.41.07-client.txt](https://github.com/Vaelzan/Scenic/files/5362874/crash-2020-10-11_22.41.07-client.txt)

here are to crash reports i always am attacking something then if i hit a Scenic block mostly grass types it crash my game with a index error

**Comment by brendenspencer** [comment]
also it is possible that's its not Scenic just it only happens when i am fighting and hit a Scenic grass block

**Comment by Vaelzan** [comment]
It isn't Scenic, but I happen to know the answer.

There's a buggy interaction between OptiFine and CoFH Core when using the newer previews of OptiFine. (see here: https://github.com/sp614x/optifine/issues/4088)

You should use this version of OptiFine instead: https://github.com/sp614x/optifine/files/4808411/preview_OptiFine_1.15.2_HD_U_G1_pre23.jar.zip

I have no idea if OptiFine will ever resolve this issue.

**Comment by brendenspencer** [comment]
Thank you
